# Welcome to Agency Jekyll Theme!

# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings

title: Hatzakis Group
description: > # this means to ignore newlines until "author:"
  Harnessing the biomolecular insights of current single molecule experiments allows us to unmask the structural and functional dynamics of important enzymes. Understanding how these enzymes operate paves the way for the design of novel pharmaceutics and biotechnological applications.
author: Hatzakis Group
keyword: jekyll
baseurl: "/" # the subpath of your site, e.g. /blog
url: "hatzakisgroup.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  "hatzakisgroup"

social:
  name: Nikos Hatzakis
  links:
    - https://twitter.com/nhatzakis
    - http://linkedin.com/in/nikoshatzakis
    - https://orcid.org/0000-0003-4202-0328

google_verify: google59e9fde1d35d1916.html

markdown: kramdown

#theme: agency-jekyll-theme #The "agency-jekyll-theme" is not supported by GitHub Pages.
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - agency-jekyll-theme.gemspec
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
